tests/FSharp.Data.Tests/JsonProvider.fs

Just ran unit tests for the 1st time and got a single failure
* Heterogeneous types with Nulls, Missing, and "" should return None on all choices
Looks like it's hard-coding 2014 as the current year.

Fix test failing in 2015

---

src/Xml/XmlInference.fs
src/Xml/XmlProvider.fs
tests/FSharp.Data.Tests/Data/Cars.xml
tests/FSharp.Data.Tests/XmlProvider.fs

This is addressing issue [discussed her eon StackOverflow](http://stackoverflow.com/questions/28515305/f-xml-data-parsing-a-subtype/28518022#28518022).
Basically, the global inference does not work on multiple samples, because we were processing the samples separately and then unifying the types. This change runs the global inference on the whole document (with multiple samples), so that the types are the same across multiple samples.

Unify types for named XML nodes accross multiple samples

---

src/CommonProviderImplementation/Debug.fs
src/CommonProviderImplementation/ProvidedTypes.fs
src/Csv/CsvGenerator.fs
src/Csv/CsvProvider.fs
src/Csv/CsvRuntime.fs
tests/FSharp.Data.DesignTime.Tests/expected/Csv,AirQuality.csv,;,,True,False,False,,,.expected
tests/FSharp.Data.DesignTime.Tests/expected/Csv,DnbHistoriskeKurser.csv,,,True,False,False,,nb-NO,.expected
tests/FSharp.Data.DesignTime.Tests/expected/Csv,LastFM.tsv,,,False,False,False,,,.expected
tests/FSharp.Data.DesignTime.Tests/expected/Csv,MSFT.csv,,,True,False,False,,,.expected
tests/FSharp.Data.DesignTime.Tests/expected/Csv,SmallTest.csv,,,True,False,False,,,.expected
tests/FSharp.Data.DesignTime.Tests/expected/Csv,Titanic.csv,,,True,False,False,,,.expected
tests/FSharp.Data.DesignTime.Tests/expected/Csv,Titanic.csv,,passengerid = int ; Pclass -&gt; Class; Parch -&gt; ParentsOrChildren = int&lt;meter&gt;;SibSp-&gt;SiblingsOrSpouse,True,True,True,,,.expected
tests/FSharp.Data.DesignTime.Tests/expected/Csv,cp932.csv,,,True,False,False,NaN (非数値),ja-JP,932.expected
tests/FSharp.Data.DesignTime.Tests/expected/Csv,file with spaces.csv,,,True,False,False,,,.expected
tests/FSharp.Data.DesignTime.Tests/expected/Csv,tendulkarHistoryWithGameNumber.csv,,,True,False,False,,,.expected
tests/FSharp.Data.DesignTime.Tests/expected/Html,SimpleHtmlTablesWithThead.htm,False,.expected
tests/FSharp.Data.Tests/CsvProvider.fs

Added append and replace-rows (`With`) methods to CsvFile, and add constructor to generated csv row type.
Constructor has optional parameters for each column but string types unfortunately default to null rather than "".
As per #578. Not sure if this is the right API, guided by `Filter` etc methods. Other caveat, I wasn't able to get the proper defaults for optional parameters in the generated constructor so that's rather 'hacked in' to avoid a NRE on saving the CSV.

Csv write API.

---

src/TypeProviderInstantiation.fs
src/Xsd/XsdGenerator.fs
src/Xsd/XsdProvider.fs
tests/FSharp.Data.DesignTime.Tests/SignatureTestCases.config
tests/FSharp.Data.DesignTime.Tests/expected/Freebase,5,True,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/WorldBank,World Development Indicators;Global Financial Development,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Xsd,gpx.xsd,True,False.expected
tests/FSharp.Data.DesignTime.Tests/expected/Xsd,purchaseOrder.xsd,True,False.expected
tests/FSharp.Data.DesignTime.Tests/expected/Xsd,xaml2006.xsd,True,False.expected
tests/FSharp.Data.Tests/Data/gpx.xsd
tests/FSharp.Data.Tests/Data/purchaseOrder.xsd
tests/FSharp.Data.Tests/Data/xaml2006.xsd
tests/FSharp.Data.Tests/FSharp.Data.Tests.fsproj
tests/FSharp.Data.Tests/XsdProvider.fs

Existing code applied default qualified/unqualified element forms to the XSD itself, think they should actually be applied to the target/instance document, see http://www.w3.org/TR/xmlschema-0/#NS
Also tried to reduce some duplication (hopefully not removed too much?), and to respect namespaces in both schema and instance doc. 
I can now parse GPX xsd as mentioned in #57, added a bunch of tests of the namespace stuff.

Sorting out qualified/unqualified forms and namespaces

---

src/Json/JsonRuntime.fs
src/Xml/XmlRuntime.fs
tests/FSharp.Data.Tests/JsonProvider.fs
tests/FSharp.Data.Tests/XmlProvider.fs

- Use the built in "Round-trip pattern" as documented here:
https://msdn.microsoft.com/en-us/library/az4se3k1%28v=vs.110%29.aspx
- Update tests to match new date-time format.

Use ISO-8601 dates in CSV and XML

---

src/Csv/CsvProvider.fs
src/Csv/CsvRuntime.fs
tests/FSharp.Data.Tests/CsvProvider.fs

For #752.
Guess I need to regenerate signature tests but putting this up for comment. In particular, I don't like the implementation, but this seemed more convenient (to put on `CsvFile<>`); and I'm not sure what the best option is for multi-row input. To throw or just take the 1st line?

Add Parse method to CsvProvider provided Row types

---

src/Json/JsonValue.fs

- Simple tweak saves 47% of work in certain tests - we basically avoid
building two identical arrays.
There is some other stuff I'm working on that I'll try to get into a decent, tested form to submit, but this is by far the biggest win with no backward compatibility issues.

Optimize conversion of resizable array to native array

---

src/Net/Http.fs

Set the default content type to "application/octet-stream" if the content type is missing in the response.
Fix for #813

Set the default content type to "application/octet-stream"

---

.gitignore
src/CommonProviderImplementation/AssemblyResolver.fs

I was tying to use F# Data on Azure with Suave using a setup similar to the one in the recent [Scot Hanselman's blog](https://github.com/shanselman/suavebootstrapper). The peculiar thing here is that this is just loading `app.fsx` using FAKE/F# Compiler Service and running it from the source code (which I quite like because it is super simple).
The problem here is that we are now running the design time component of F# Data on a machine that does not have anything installed and so it was failing to load `FSharp.Core.dll` version 4.3.0.0. I was running this via  FAKE which has correct binding redirects and I had 4.3.1.0 in the folder, but it was still failing.
The code was failing [here](https://github.com/fsharp/FSharp.Data/blob/master/src/CommonProviderImplementation/AssemblyReplacer.fs#L …

Do not use reflection only if it would fail

---

src/Net/Http.fs

I've created a convenience function for sending http requests with Basic Auth.  Usage will look like:
```
Http.RequestString
( "http://httpbin.org/post", 
headers = [ BasicAuth "user" "password" ],
body = TextRequest """ {"test": 42} """)
```
I'm not 100% convinced this belongs in the HttpRequestHeaders module, since it actually uses the Authorization header that is already in there.  An alternative would be to have a function that simply returns the encoded string and leaves it to the consumer to pipe this into the Authorization header, something like
```
Http.RequestString
( "http://httpbin.org/post", 
headers = [ BasicAuth "user" "password" |> Authorization ],
body = TextRequest """ {"test": 42} """)
```
I'm not sure exactly where such a function would belong however.

Convenience function for Basic Auth

---

src/CommonRuntime/StructuralInference.fs

In mono 4, the workaround is not only no longer needed, but it actually does not work.
This is the most conservative thing I could come up with - try the call normally
(works on .NET and Mono 4+) and if that fails with the Mono 3 error, do the workaround!

Workaround for an era workaround for mono 4

---

src/Csv/CsvRuntime.fs
tests/FSharp.Data.Tests/CsvProvider.fs

Allowing users of CsvProvider to generate types from csv where data rows end by a single separator.

Fixes #830. CsvProvider - allowing data row to be ended with a single separator

---

build.fsx
paket.dependencies
paket.lock
tests/TestApps/Test.fs

Fixes #851. The root cause is `paket-files` not being committed in the Git repo. It would be great if they were committed in the repo so that they could be source indexed. I only marked this work in progress because it isn't published yet to the NuGet Gallery, but you are welcome to merge it and upgrade when I do an official release.

ignore paket-files & upgrade SourceLink

---

tests/FSharp.Data.Tests/JsonParserProperties.fs

fsharp/FSharp.Data#860
The JsonParser is working correctly. The test/property is expecting the
unicode literal within the string to be the unicode character.
add an unescape method for the tests and two tests to demonstrate that it is fixed.

fix #860 FsCheck Failure in JsonParser

---

src/Html/HtmlInference.fs

When use createDefinitionListType function with description list (dl) containing no value the inferListType function throw an ArgumentException on "Seq.reduce" because input sequence is empty
Here is a simple Html that reproduce the bug
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
<dl>
<dt><a id="l1" title="My link" href="http://foo.com" target="_blank">Foo</a></dt>
<dt><a id="l2" title="My link" href="http://foo.com" target="_blank">Foo2</a></dt>
</dl>
</body>
</html>

Fix HtmlInference inferListType when passing an empty seq

---

src/CommonRuntime/Caching.fs

Cache timestamp should be deducted from the current time, not the other
way round

Fixed the never expiring in-memory cache

---

docs/content/library/HtmlProvider.fsx

Someone removed the `Viewers (millions) - Average` column.

Update HtmlProvider docs to reflect Doctor Who wiki changes

---

src/CommonProviderImplementation/AssemblyResolver.fs

WebRequest.DefaultWebProxy is null in some environments. Setting the Credentials property was causing a NullReferenceException.

Fix issue #907 NRE

---

src/Csv/CsvRuntime.fs
tests/FSharp.Data.Tests/CsvProvider.fs

according to RFC 4180:
> Fields containing line breaks (CRLF), double quotes, and commas
>        should be enclosed in double-quotes.

Fields containing double quotes should be enclosed in double-quotes

---

build.fsx
nuget/FSharp.Data.nuspec
nuget/linqpad-samples/GitHub.linq
nuget/linqpad-samples/Jira.linq
nuget/linqpad-samples/TypeInference.linq

LINQPad is excellent for prototyping and supports F#.
However, in free version, NuGet is only available for packages that include LINQPad samples: https://www.linqpad.net/nugetsamples.aspx
This PR:
* Makes FSharp.Data NuGet package visible in free LINQPad version
* Makes it easier to get started and play around with FSharp.Data

Add LINQPad samples to NuGet package

---

paket.lock
src/CommonProviderImplementation/AssemblyResolver.fs

More about this here: https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/pull/104
This is a fairly serious bug that means CSV provider does not work when used via FsLab. 
@ovatsus What are your current release plans? Do you think we could release this soon? (Sometime this week would be ideal.)

Safer assembly replacement - fix CSV provider in FsLab

---

src/Net/Http.fs

if the set-cookie header in the response is not correct, the request fails.
this change permit to get the response by rejecting cookies with not well formated associated uri
#960

[Http] don't produce cookies from response header if associated uri is not valid

---

RELEASE_NOTES.md
src/Net/Http.fs

> Otherwise it is assumed to be DateTimeKind.Local (local time)
https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.date(v=vs.110).aspx

Specify kind on Date header

---

RELEASE_NOTES.md
src/Html/HtmlCssSelectors.fs
tests/FSharp.Data.Tests/HtmlCssSelectors.fs

Supports ` \x` escaping where x is any character with the exception of `CR`, `LF`, `FF` and
a hexadecimal digit (per CSS 2.1 spec).

Add support for escaped characters in the css selectors.

---

tests/FSharp.Data.Tests/Http.fs

Fixes the failing tests in Http.fs, addresses issue #986

updated Http tests to not rely on json response from 3rd party

---

src/Net/Http.fs

When using the time out feature on StartChild to end an Async Http Request we also need to call Abort() on the HttpWebRequest. See [MSDN.](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.abort(v=vs.110).aspx)
When StartChild times out and Abort is not called - the next request causes the ServicePoint to allocate a new connection as the timed out connection is still tied up (indefinitely). Eventually you will reach DefaultConnectionLimit and all requests return time outs. This issue is especially noticeable when DefaultConnectionLimit is set to a very low value. A work around is to call CloseConnectionGroup() on the ServicePoint as soon as a StartChild time out is thrown. 
Adding Abort() means a work around is no longer required.

Call Abort() when we "manually" time out a request with StartChild.

---

src/Html/HtmlRuntime.fs
tests/FSharp.Data.DesignTime.Tests/expected/Html,doctor_who2.html,False,False,.expected
tests/FSharp.Data.DesignTime.Tests/expected/Html,us_presidents_wikipedia.html,False,False,.expected
tests/FSharp.Data.DesignTime.Tests/expected/Html,wimbledon_wikipedia.html,False,False,.expected
tests/FSharp.Data.DesignTime.Tests/expected/WorldBank,World Development Indicators;Global Financial Development,True.expected
tests/FSharp.Data.Tests/HtmlProvider.fs

Issue #989 is about the fact that the `Documentation generated correctly ("library/HtmlProvider.fsx")` test fails, because the `Viewers (millions) - Finale` column is missing. It is missing because the column count of the `Series overview` table  on https://en.wikipedia.org/wiki/List_of_Doctor_Who_serials is off by one. If you look at this table closely, you will notice that all the cells in the "Episodes" column have a colspan of 2, for no obvious reason. This causes the column count too be low by 1.
So the fix is to account for the colspans when determining the number of columns in a table.

Fix for issue #989: Dr. Who in Trouble

---

src/Net/Http.fs

When running the unit tests (as of commit 0b54be6) via `build.cmd all`, or via running the tests in `FSharp.Data.Tests.sln` on Windows 10, I get the following error:
1) Failed : FSharp.Data.Tests.HttpIntegrationTests.all of the manually-set request headers get sent to the server
Expected: 2000-12-31 11:59:59.000
But was:  2000-12-31 19:59:59.000
at FsUnit.TopLevelOperators.should[a,a](FSharpFunc`2 f, a x, Object y) in d:\GitHub\FsUnit\src\FsUnit.NUnit\FsUnit.fs:line 44
at FSharp.Data.Tests.HttpIntegrationTests.all of the manually-set request headers get sent to the server() in C:\Users\jas\Develop\Github\FSharp.Data\tests\FSharp.Data.Tests\HttpIntegrationTests.fs:line 131
The time is off by 8 hours, which is a clue, as I am on PST. Closer inspection reveals that the header field that …

Fix test failure when machine time is not set to UTC

---

src/Html/HtmlParser.fs
tests/FSharp.Data.Tests/HtmlParser.fs

My use-case involves parsing a HTML document with "large" CDATA sections (80KiB).
The existing implementation seemingly hanged but in truth was just progressing very slowly.
The problem seemed to be that for every CDATA character this was performed:
```fsharp
if ((!state.Content).ToString().EndsWith("]]>"))
````
ToString is implemented like this:
```fsharp
override x.ToString() = String(x.Contents |> List.rev |> List.toArray)
```
So for each CDATA character we reverse the current content, makes it into an array and then creates a string.
Instead I changed cData to accept a parameter which controls whether an end tag is being processed.
In addition, I added a unit test for the performance for parsing large CDATA sections. Also, it seems that the CDATA sub parser wasn't triggered for the …

Improved performance when parsing CDATA sections

---

src/CommonRuntime/TextRuntime.fs

Caches CultureInfo per Thread in order to improve DateTime parsing when parsing with specific Culture
The idea for this optimization started from this StackOverflow question: https://stackoverflow.com/questions/42469637/
Performance numbers:
Parsing 100000 dates
Using cached CultureInfo object...
took 114 ms
Using updated TextRuntime.GetCulture...
took 144 ms
Using fresh CultureInfo object (same technique as old TextRuntime.GetCulture)...
took 52556 ms

Introduced thread-affine CultureInfo cache

---

src/Html/HtmlCssSelectors.fs
src/Html/HtmlOperations.fs
tests/FSharp.Data.Tests/HtmlCssSelectors.fs

Added  .Html and tryGetHtml functionality so that css selectors can be done from html tag level instead of body level

Fix cssselector to work outside the body element

---

docs/content/library/HtmlProvider.fsx
src/Html/HtmlParser.fs
tests/FSharp.Data.DesignTime.Tests/expected/Html,ebay_cars.htm,False,False,.expected
tests/FSharp.Data.Tests/HtmlParser.fs

This PR fixes #1022 and also implicitly closed li list items, like the following
```
<ul>
<li>1
<li>2
<li>3
</ul>
```

Fix #1022: HtmlProvider Self closing table tags

---

src/Json/JsonValue.fs
tests/FSharp.Data.Tests/JsonValue.fs

Perhaps the dumbest PR so I understand if this is rejected but, that being said, here it is!
My reasons for submitting it are
- Wrapping in option helps with an functional style, rather than having exceptions and, selfishly
- I write this same wrapper in every project that uses FSharp.Data.
Let me know your thoughts!

Add `JsonValue.TryParse`

---

src/Html/HtmlParser.fs
tests/FSharp.Data.Tests/HtmlParser.fs

Whilst investigating original issue I've found a few more cases when parser would mistake special characters for end tag sequence.

Additional parsing for scripts

---

src/Net/Http.fs
tests/FSharp.Data.Tests/Http.fs

Http.fs cooking handling was calling split('='), removing all '=' from the string whereas the goal was just to split name and value. This bug was introduced in PR #945.
I added a test and reused code before #945 searching for firstEqual with indexOf. I kept a guard if it was not found (since it was the logic implemented with split('=')), but not sure to understand what is the intent (cookie with only a name ?)...

Fix incorrect cookie value when it contains '=' sign

---

docs/content/ja/library/CsvProvider.fsx
docs/content/library/CsvProvider.fsx
src/Net/Http.fs
tests/FSharp.Data.Tests/Http.fs

This patch is intended to fix #1104. `Uri.EscapeDataString` fails to handle more than 32k characters, but `application/x-www-form-urlencoded` has no such restriction. While `WebUtility.UrlEncode` is [not quite sufficient](https://blogs.msdn.microsoft.com/yangxind/2006/11/08/dont-use-net-system-uri-unescapedatastring-in-url-decoding/) for correct encoding, a simple `Replace` fix can make it work.

Fix form body url encoding #1104

---

tests/FSharp.Data.DesignTime.Tests/DocumentationTests.fs

The documentation generation tests on windows have failed the build on master for quite some time now, despite working on mono across OSX and Linux.  This PR just disables those tests on windows to green up the build again.  A recent PR re-enabled them but now, whether due to floating versions of compiler changes they fail consistently.  At least we're still running them on Mono?

[Build] turn off doc gen tests on windows because of errors

---

.gitignore
RELEASE_NOTES.md
docs/content/library/HtmlProvider.fsx
docs/content/library/JsonProvider.fsx
src/Csv/CsvFile.fs
src/Html/HtmlParser.fs
src/Json/JsonValue.fs
tests/FSharp.Data.Tests/Http.fs

Should fix #871.
We do default to UTF8 if no encoding is specified, but now there are no longer any "" parameters passed as encodingStrings to the asyncReadTextAtRuntime function.

thread encodings through the load methods

---

src/Net/Http.fs

The application/json-rpc should be treated as text. See http://www.jsonrpc.org/historical/json-rpc-over-http.html.

Added application/json-rpc to mimetype and isText.

---

src/Html/HtmlParser.fs
tests/FSharp.Data.Tests/HtmlParser.fs

When parser is in a script mode and encounters " or ' it detects string literal and will consume characters until it finds matching " or ' correspondingly. However, " or ' can be escaped, so that they loose their original meaning and should be ignored by the parser at that point. Parser should look for next " or '.

Fix handling of excaped charaters in string literals within script tag

---

src/Net/Http.fs

I've added a module of HTTP Status Codes to Http.fs for issue #1163. I have only included official status codes, and did not include the chocolate teapot (418) Easter egg code (I did consider it!). 
The comments are abbreviated or complete copies of the status code descriptions found here -  https://en.wikipedia.org/wiki/List_of_HTTP_status_codes. 
Let me know if you would like anything changed, or if I missed anything - this is my first pull request!

Status codes added to Http.fs

---

src/Json/JsonConversions.fs
src/Json/JsonInference.fs
tests/FSharp.Data.Tests/JsonProvider.fs

Sufficiently large float values will end up converted as Int.MinValue and succeed

Don't silently convert floats to integers in JsonProvider.

---

README.md
build.fsx
src/FSharp.Data.DesignTime/FSharp.Data.DesignTime.fsproj
src/FSharp.Data/FSharp.Data.fsproj
tests/FSharp.Data.Tests/FSharp.Data.Tests.fsproj

I don't know what has changed but it seems that after upgrading to the .NET SDK 2.1.401 we now have to use
<DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
to disable the implicit FSharp.Core reference.  Previously this was disabled automatically if you have an FSharp.Core reference in your project file.

fix build - add DisableImplicitFSharpCoreReference

---

src/FSharp.Data.DesignTime/FSharp.Data.DesignTime.fsproj
src/FSharp.Data/FSharp.Data.fsproj

The F# SDK seems to be overriding the assemblyinfo.fs values where they exist. Adding the `GenerateAssemblyInfo` flag set to false returns that file to its place of primacy.
Before: 
```
➜  FSharp.Data git:(fix-assembly-version) ✗ monop -r bin/Debug/net45/FSharp.Data.dll
Assembly Information:
FSharp.Data
Version=1.0.0.0
Culture=neutral
PublicKeyToken=null
```
After:
```
➜  FSharp.Data git:(fix-assembly-version) ✗ monop -r bin/Debug/net45/FSharp.Data.dll
Assembly Information:
FSharp.Data
Version=3.0.0.0
Culture=neutral
PublicKeyToken=null
```

Fix assembly version generation

---

src/CommonRuntime/NameUtils.fs

Issue: Crashes when loading an html page with a table with a zero length name 
Fix: If uniqueGenerator is passed a name value of length 0 the name is defaulted to 'Unnamed'.

Issue #1167

---

docs/content/library/XmlProvider.fsx

just thought of mentioning the XSD option at the beginning of XML documentation in order to ease discoverability.

Add XSD option in docs

---

src/Csv/CsvRuntime.fs

This fixes a small bug where the CSV Save functions don't dispose the writers they use, and therefore leave stream flushing and potentially file handles open until garbage collection cleans up the writers. I've simply changed the `let writer`s to `use writers` to ensure they are disposed correctly.
One point that's worth some discussion: for the `Save(stream : Stream ...` overload, I've made it so that the save does not close the underlying stream. Instead, the writer flushes into it, but leaves it open. I chose to do this because I'm of the opinion that if I give a stream to something, I (the caller) own it and I will close and dispose it when I'm done with it. I don't expect `Save` to close and dispose it for me.
However this is not the default behaviour when you pass a Stream to a …

Fixed undisposed writers in CSV saving

---

RELEASE_NOTES.md
src/CommonProviderImplementation/Helpers.fs

The F# tools appear to be leaking type provider instances from time to time.  Or, perhaps FSharp.Data is not de-registering file watcher callbacks correctly.
Either way, best practice is that file watcher callbacks do not hold strong handles to type providers.

Reduce impact of leaking type provider instances

---

src/CommonProviderImplementation/Helpers.fs

I'm convinced 5 minutes is too long to be caching these instances under many user edits which might recreate many type provider instances
I'm also sceptical about the cache in general, see #1253 - I'd much prefer this is scoped to a particular TP instance - but for now decreasing the cache time seems sensible.
This is all part of a range of work to try to reduce the impact of some memory problems we're seeing in when using F# tooling with FSharp.Data type providers

decrease cache time

---

src/Json/JsonValue.fs
tests/FSharp.Data.Tests/JsonValue.fs

Quick stab at fixing #1261. Seems to work now with the second fix applied.

Remove obsolete special-case root value parsing.

---

nuget/FSharp.Data.nuspec

NuGet packages are moving away from using `licenseUrl` to a `license` field (see [this announcement](https://github.com/NuGet/Announcements/issues/32)).
The spec for the change is [here](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg).
This change updates the FSharp.Data nuspec file to use the new format.

Updating license in nuspec

---

src/Json/JsonValue.fs
tests/FSharp.Data.Tests/JsonValue.fs

Unfortunately `System.Double.NaN`, `System.Double.PositiveInfinity` and `System.Double.NegativeInfinity` cause invalid JSON to be generated. These seem like special cases that shouldn't happen often but they are not disallowed by the type system.
I was using FsCheck to generate `JsonValue` instances and I noticed an array containing `NaN` which causes JSON parsers to error.
This change attempts to mimic the decisions already made in JavaScript, e.g.
``` javascript
$ node
> JSON.stringify(NaN)
'null'
> JSON.stringify(Infinity)
'null'
> JSON.stringify(-Infinity)
'null'
```

Handle serialization of odd float values

---

src/FSharp.Data/FSharp.Data.fsproj
src/Html/HtmlActivePatterns.fs
src/Html/HtmlParser.fs

Support for https://github.com/fsharp/FSharp.Data/issues/1102

Adding HTML active patterns to expose internals of HtmlNode.

---

src/Html/HtmlCssSelectors.fs
src/Html/HtmlOperations.fs
tests/FSharp.Data.Tests/HtmlCssSelectors.fs
tests/FSharp.Data.Tests/HtmlParser.fs

Fix for #1212 
When calling `CssSelect` on an `HtmlDocument`, it first selects the html tag and applies the selector to that to find matching descendants. But if the `HtmlDocument` doesn't have an html tag this fails and according to the [HTML Specificaton](https://html.spec.whatwg.org/multipage/syntax.html#optional-tags) this is valid.
I changed the implementation of  `CssSelect(doc:HtmlDocument, selector)` from `doc.Html()` to `doc.Elements()` in order to apply the selector to all the root tags of the document. If the root tag is html, then it will work as before, but now it will also work if you have a page that omits it and therefore has multiple root tags, like for example:
```
<head>
<title>Hello</title>
</head>
<body>
<p>Welcome to this example.</p>
</body>
```
Please let me know …

#1212 CssSelect fails when there is no html tag

---

src/Net/Http.fs

The current `FSharp.Data.WebResponse` wrapper does not easily allow the user to access the original response.
In particular, the `WebResponse` will normally (always?) be a `HttpWebResponse`, which exposes critical properties like `StatusCode`, which are currently buried pretty deep under type tests (and I might not have found them at all without debugging and looking at the source):
```fsharp
function 
| Error (e : Net.WebException) ->
match e.InnerException with
| :? Net.WebException as webExn ->
match webExn.Response with
| :? Net.HttpWebResponse r when r.StatusCode = Net.HttpStatusCode.Conflict -> 
Log.Informationf("`Resource %s already exists, no operation needed", resourceName)
Ok ()
```
This PR adds to `FSharp.Data.WebResponse:`
- a set of properties that wrap those in …

Expose InnerResponse, Http properties

---

src/Net/Http.fs
tests/FSharp.Data.DesignTime.Tests/SignatureTestCases.config
tests/FSharp.Data.Tests/Http.fs

fixes #1263 
Escape query strings using `Uri.EscapeDataString` instead of `Uri.EscapeUriString`, this should correctly escape all URI reserve characters so they can be used as literals in query strings.
- Updated failing test
- Added specific unit test

Modified escaping of query string parameters

---

README.md
docs/content/ja/library/CsvProvider.fsx
docs/content/ja/library/JsonProvider.fsx
docs/content/ja/library/XmlProvider.fsx
docs/content/library/CsvProvider.fsx
docs/content/library/HtmlProvider.fsx
docs/content/library/JsonProvider.fsx
docs/content/library/WorldBank.fsx
docs/content/library/XmlProvider.fsx
nuget/FSharp.Data.3.0.1.nuspec
nuget/FSharp.Data.nuspec
performanceAnalysis.fsx
tests/FSharp.Data.Tests/HtmlCharRefs.fs

Because of https://github.com/fsprojects/FSharp.Data/issues/1340 and https://github.com/fsprojects/FSharp.Data/issues/1306 we should just ask people to add `ResolutionFolder=__SOURCE_DIRECTORY__` to all examples that use relative path names.

add ResolutionFolder=__SOURCE_DIRECTORY__ to docs

---

docs/tools/generate.fsx

Recently FSharp.Data was moved into fsprojects organization breaking some links.

fix links in docs/tools/generate.fsx

---

src/CommonRuntime/Pluralizer.fs
tests/FSharp.Data.Tests/NameUtils.fs

Currently, "releases" takes the "sis" <-> "ses" suffix rule, and therefore becomes "releasis" when converted from plural to singular.
This patch fixes the problem by adding "release" as a special word, so that `toSingular` correctly resolves the singular form.

NameUtils/Pluralizer: Fix unusual singularizations for some common words (choices; releases)

---

src/Json/JsonValue.fs
tests/FSharp.Data.Tests/JsonValue.fs

Rewrote a few functions in CPS allowing for deeper structures without stack overflow.

Tail recursive parse

---

src/CommonRuntime/Caching.fs

Bug was spotted and reported on Slack today - as it stands, nothing is ever invalidated because we pretty much eternally live in negative date-time space, which will always be less than a positive TimeSpan.

Fix internet cache invalidation

---

paket.dependencies
paket.lock

Fixes #1376 to remove the errant sourcelink dependency.
After this change, the nuspec contains the following dependency groups:
```xml
<dependencies>
<group targetFramework=".NETStandard2.0">
<dependency id="FSharp.Core" version="4.7.2" exclude="Build,Analyzers" />
</group>
</dependencies>
```

set sourcelink to be a private asset so that it doesn't get added to package dependencies

---

.gitattributes

Fixes #1380 by performing the suggested action from that issue.

Update .gitattributes to fix file type attributions in GitHub

---

src/FSharp.Data.DesignTime/FSharp.Data.DesignTime.fsproj
src/FSharp.Data/FSharp.Data.fsproj

I accidentally included the snk file in the fsproj, which caused nuget to include the reference when building the nupkg and subsequently deploying it along with the DLL. This led to the snk file being installed in all projects that referenced FSharp.Data. 
My apologies.

Removing snk file from fsproj references

---

src/Html/HtmlParser.fs
tests/FSharp.Data.Tests/HtmlParser.fs

See https://github.com/fsprojects/FSharp.Data/issues/1264

@tomakita's ampersand parsing fix

---

src/Net/Http.fs

newline required before writing next boundary and header of subsequent files, otherwise server will only decode first file.

Correction to positioning of boundary delimiter with multiple multipart/form-data files

---

src/Net/Http.fs
tests/FSharp.Data.Tests/Http.fs

Test for multipart data

---

docs/library/CsvFile.fsx
docs/library/CsvProvider.fsx
docs/library/HtmlParser.fsx
docs/library/XmlProvider.fsx

The docs are now showing F# Interactive processing outputs 
These reduces the amount of information shown

fix docs output lengths

---

.github/workflows/pull-requests.yml
src/AssemblyInfo.DesignTime.fs
src/AssemblyInfo.fs
src/Csv/CsvRuntime.fs
src/FSharp.Data.DesignTime/FSharp.Data.DesignTime.fsproj
src/FSharp.Data/FSharp.Data.fsproj
src/Json/JsonValue.fs
src/Net/Http.fs
tests/FSharp.Data.Tests/FSharp.Data.Tests.fsproj
tests/FSharp.Data.Tests/JsonProvider.fs
tests/FSharp.Data.Tests/Program.fs

Fixes https://github.com/fsprojects/FSharp.Data/issues/1410, a problem building the debug version of this repo with F# 6.
1. It turns out Debug build of FSharp.Data.Tests was busted for a while with F# 5 because tailcalls weren't being taken during JSON parsing.  
2. When turning on explicit tailcalls for debug code, the problem went away with F# 5 but remains for F# 6 because of https://github.com/dotnet/fsharp/issues/12413.  
3. The code changes workaround this
Also adds a debug build to the PRs

fix stack overflow when building debug code

---

src/Html/HtmlParser.fs
tests/FSharp.Data.Tests/HtmlParser.fs

Quoting from
https://www.w3.org/TR/2011/WD-html-markup-20110113/syntax.html#void-element
> The following is a complete list of the void elements in HTML:
> area, base, br, col, command, embed, hr, img, input, keygen, link,
> meta, param, source, track, wbr
[...]
> Void elements only have a start tag; end tags must not be specified
> for void elements.
> A non-void element must have an end tag, unless the subsection for
> that element in the HTML elements section of this reference indicates
> that its end tag can be omitted.

HtmlNode.ToString(): fix self-closing tags on empty non-void elements

---

src/Html/HtmlParser.fs
tests/FSharp.Data.Tests/HtmlParser.fs

At the same time the assumption that the code element is formatted is not correct. They are often used at the same time though and with that comes another issue: keeping FormattedMode in elements nested into pre.
I'm not sure how to approach this, I've never worked with refs like here before. Would it be ok to drop the FormattedMode and add an IsFormatted: bool ref instead? And update that when entering/exiting pre elements.

HtmlState: restore FormattedMode if still in pre after char ref

---

src/Net/Http.fs
tests/FSharp.Data.Tests/Http.fs

Implementation and tests - non seekable multipart form files

---

src/Net/Http.fs
tests/FSharp.Data.Tests/Http.fs

As reported in #1420 , two extra bytes of newline is appended to the last Multipart Item, this PR aims to fix it.
Since extra newline removed, two existing test cases shall be revised to reflect this change:
- ``correct multipart content format``
- ``Seekable streams create Seekable CombinedStream``
I have tested several scenarios on number of files,  format, size etc. upon the built FSharp.Data.dll and looks good.

Proposed fix to #1420 on extra newline before endBoundaryStream

---

src/CommonProviderImplementation/Helpers.fs
src/Csv/CsvProvider.fs
src/Html/HtmlProvider.fs
src/Json/JsonProvider.fs
src/Xml/XmlProvider.fs
tests/FSharp.Data.DesignTime.Tests/SignatureTests.fs
tests/FSharp.Data.DesignTime.Tests/expected/Json,Dates.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,DoubleNested.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,Empty.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,GitHub.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,Nested.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,OptionValues.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,Simple.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,SimpleArray.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,TimeSpans.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,TwitterSample.json,True,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,TwitterStream.json,True,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,TypeInference.json,False,,,False.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,TypeInference.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,Vindinium.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,WikiData.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,WorldBank.json,False,WorldBank,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,contacts.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,optionals.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,projects.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,reddit.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,topics.json,True,Topic,,True.expected
tests/FSharp.Data.Tests/JsonProvider.fs

Added overload of Load method on JsonProvider to support combining JsonProviders without need for additional conversion to and from string. This should fix #1309

JsonProvider.Load(value: JsonValue)

---

docs/library/CsvProvider.fsx

See https://fsprojects.github.io/FSharp.Data/reference/fsharp-data-csvprovider.html#Separators

Typo fix, the parameter is plural ("Separators")

---

docs/library/CsvProvider.fsx

Log message shamelessly lifted from nhirschey's previous commit. :-)

Typo fix, the parameter is plural ("Separators").

---

src/Html/HtmlOperations.fs
src/Html/HtmlRuntime.fs
tests/FSharp.Data.Tests/HtmlOperations.fs

This pull request addresses #1292. It seems like the current version of `innerTextExcluding'` was tightly coupled to some of the implementation details of the Html type provider. In order to avoid breaking the `Validate signature didn't change` tests, I moved the existing logic to private functions inside `HtmlRuntime.fs`. Then I added a new simpler implementation to `HtmlOperations.fs` which doesn't modify the exclusion list or filter on the `aria-hidden` attribute.

Remove restrictions for getting innerText

---

build.fsx
src/CommonProviderImplementation/Helpers.fs
src/CommonRuntime/IO.fs
src/CommonRuntime/StructuralInference.fs
src/CommonRuntime/StructuralTypes.fs
src/CommonRuntime/TextRuntime.fs
src/Csv/CsvExtensions.fs
src/Csv/CsvGenerator.fs
src/Csv/CsvInference.fs
src/Csv/CsvProvider.fs
src/Html/HtmlGenerator.fs
src/Html/HtmlProvider.fs
src/Json/JsonConversionsGenerator.fs
src/Json/JsonExtensions.fs
src/Json/JsonGenerator.fs
src/Json/JsonInference.fs
src/Json/JsonProvider.fs
src/Json/JsonRuntime.fs
src/Json/JsonValue.fs
src/Net/Http.fs
src/WorldBank/WorldBankProvider.fs
src/WorldBank/WorldBankRuntime.fs
src/Xml/XmlGenerator.fs
src/Xml/XmlProvider.fs
tests/FSharp.Data.DesignTime.Tests/InferenceTests.fs
tests/FSharp.Data.Tests/JsonProvider.fs
tests/FSharp.Data.Tests/JsonValue.fs

pre-clean some code before applying fantomas

---

build.fsx
paket.dependencies
paket.lock
tests/FSharp.Data.DesignTime.Tests/paket.references
tests/FSharp.Data.Reference.Tests/paket.references
tests/FSharp.Data.Tests.CSharp/paket.references
tests/FSharp.Data.Tests/paket.references

This adds [Tyrrrz/GitHubActionsTestLogger](https://github.com/Tyrrrz/GitHubActionsTestLogger) so that it's easier for test results to be viewed for a particular CI run.  This test logger will only be used if you're on a CI run.

add GithubActionsTestLogger and use it in CI builds

---

tests/FSharp.Data.Tests/FSharp.Data.Tests.fsproj
tests/FSharp.Data.Tests/Http.fs

The CI for #1447 already failed two times, so let's see if this PR improves the situation...
I initially thought the problem was simply that using an external (internet) endpoint for the tests was unreliable, but the tests were still failing a bit randomly after replacing the remote endpoints with a local http test server.
After investigation, I believe there is a race condition between the http stack timeout and the `Async.StartChild` timeout. (in `getResponse` in `Http.fs`)  
If the http stack timeout is triggered first, the inner exception is null. Since the tests were asserting that the inner exception should be a `TimeoutException`, they were failing in this case.
In all cases, the `WebException` status should indicate a timeout, so I changed the assertion accordingly...

Fix http tests

---

docs/library/HtmlProvider.fsx
docs/library/JsonProvider.fsx
docs/library/XmlProvider.fsx

As a follow up PR for #1447, here is some documentation about the feature!
The branch is currently on top of the previous PR branch.  
Please ignore all but the last two commits until the previous PR is merged and this one is rebased.
Note the TODO in the latest commit: I'm not sure which version will contain this new feature, so I left a `version TBD` that will have to be replaced before we merge the docs.

Inline schemas docs

---

FSharp.Data.sln
docs/library/WorldBank.fsx
src/FSharp.Data.Csv.Core/FSharp.Data.Csv.Core.fsproj
src/FSharp.Data.DesignTime/FSharp.Data.DesignTime.fsproj
src/FSharp.Data.Html.Core/FSharp.Data.Html.Core.fsproj
src/FSharp.Data.Http/FSharp.Data.Http.fsproj
src/FSharp.Data.Json.Core/FSharp.Data.Json.Core.fsproj
src/FSharp.Data.WorldBank.Core/FSharp.Data.WorldBank.Core.fsproj
src/FSharp.Data.Xml.Core/FSharp.Data.Xml.Core.fsproj
src/FSharp.Data/FSharp.Data.fsproj
tests/FSharp.Data.Core.Tests.CSharp/FSharp.Data.Core.Tests.CSharp.csproj
tests/FSharp.Data.Core.Tests/FSharp.Data.Core.Tests.fsproj
tests/FSharp.Data.DesignTime.Tests/FSharp.Data.DesignTime.Tests.fsproj
tests/FSharp.Data.Reference.Tests/FSharp.Data.Reference.Tests.fsproj
tests/FSharp.Data.Tests/FSharp.Data.Tests.fsproj

Fixes #1463 and makes it easier to manage paket files since they are now visible in the solution.
I also took the liberty to re-add solution level items missing or with broken paths.

Remove explicit PackageReference in projects + include paket.references

---

docs/library/HtmlProvider.fsx

It seems as though in [this commit](https://github.com/fsprojects/FSharp.Data/commit/d12f4e9b9d2cd2f8f01bd39503003831487aa578) one of the examples for the HTML type provider was changed from scraping market data to the F1 calendar, but the rest of the documentation and comments was not updated to match. I noticed this while looking through the docs so here is a fix.

Updated documentation for HTML type provider example

---

RELEASE_NOTES.md
src/CommonRuntime/StructuralInference.fs
src/FSharp.Data.Http/FSharp.Data.Http.fsproj
src/FSharp.Data.Http/PublicApi.fs
src/Xml/XmlProvider.fs
tests/FSharp.Data.DesignTime.Tests/TypeProviderInstantiation.fs

This is a breaking change, but I feel like it's needed...
Using `FSharp.Data.Runtime.StructuralInference` was a mistake (sorry, my bad). It should not be necessary to reference that namespace just to initialize a type provider...
I moved the enum to the `FSharp.Data` namespace instead, the same as the providers so it's readily available:
- Nothing has to be explicitly `open`ed to use the enum with a type provider.
- This will hopefully make the breaking change less painful since it is likely to still compile after the update.
I have no idea how much this new-ish enum is used in the wild, but since it's optional and a bit obscure, it might not impact too many users...
Since the next version will be the new major version 6.x and it's still currently in beta, I think this is a good …

Change the namespace of the public "InferenceMode" enum

---

src/Csv/CsvRuntime.fs
tests/FSharp.Data.Core.Tests/CsvReader.fs

When using the `FSharp.Data.Csv.Core` package to read massive CSV data from an AWS S3 bucket we had some issues because sometimes many rows got lost.
The problem seems to be related to the `StreamReader.Peek()` method that is used. When `StreamReader.Peek()` returns `-1` the whole reading stops with the current implementation. The [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamreader.peek?view=net-7.0) states that `-1` is not only returned in case of the end of the stream, but also if the stream is not seekable and the stream doesn't read all data that was requested.
> An integer representing the next character to be read, or -1 if there are no characters to be read or if the stream does not support seeking.
This can be fixed by using `StreamReader.Read()` …

Fix reading CSV from non seekable network stream

---

src/CommonProviderImplementation/ConversionsGenerator.fs
src/CommonProviderImplementation/Helpers.fs
src/Csv/CsvProvider.fs
src/Html/HtmlGenerator.fs
src/Json/JsonConversionsGenerator.fs
src/Json/JsonGenerator.fs

This makes it easier to debug and follow the code since the IDE is able to find the referenced methods and display their signature at the location they are used.
This is only a technical refactoring. Functionally, nothing should have changed.

Use `nameof` for all dynamically built quotations

---

RELEASE_NOTES.md
src/FSharp.Data.DesignTime/Json/JsonGenerator.fs
tests/FSharp.Data.DesignTime.Tests/SignatureTestCases.config
tests/FSharp.Data.DesignTime.Tests/expected/Json,DictionaryInference-arrays.json,False,,,True,False,BackwardCompatible.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,DictionaryInference-arrays.json,False,,,True,False,ValuesAndInlineSchemasHints.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,DictionaryInference-arrays.json,False,,,True,False,ValuesAndInlineSchemasOverrides.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,DictionaryInference-arrays.json,False,,,True,False,ValuesOnly.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,DictionaryInference-arrays.json,False,,,True,True,BackwardCompatible.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,DictionaryInference-arrays.json,False,,,True,True,ValuesAndInlineSchemasHints.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,DictionaryInference-arrays.json,False,,,True,True,ValuesAndInlineSchemasOverrides.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,DictionaryInference-arrays.json,False,,,True,True,ValuesOnly.expected
tests/FSharp.Data.Tests/Data/DictionaryInference-arrays.json

Before this PR, the generation is wrong:
This is because the records inferred originally in the arrays are normally supposed to have the name of the property declaring them (`123` and `789` in the screenshots), and two similar records with a different name are not merged.
This problem was taken care of by the original `PreferDictionaries` implementation when values are records (by dropping the record's name), but not when the values are arrays of records!
After this PR, the names of records nested in an array are also dropped, which yields the expected result, with records properly merged in a single type:
(PR of the original implementation for reference: https://github.com/fsprojects/FSharp.Data/pull/1430)
---
_Note: This PR contains only 2 commits, but is currently on top of the …

Fix generated code of the json provider with `PreferDictionaries` when values are arrays

---

src/FSharp.Data.Json.Core/JsonValue.fs

This PR resolves https://github.com/fsprojects/FSharp.Data/issues/1482.
* Add a new case in `JsonSaveOptions`
* Updated serialization method `WriteTo`
* Passed the tests
https://github.com/bonjune/FSharp.Data/blob/39da6c2d6a841baee019cd03439ad9240b5b91c7/src/FSharp.Data.Json.Core/JsonValue.fs#L20-L32

New option for JSON serialization (#1482)

---

src/FSharp.Data.Csv.Core/CsvRuntime.fs
tests/FSharp.Data.Tests/CsvProvider.fs

https://github.com/fsprojects/FSharp.Data/issues/1481

Adhere to RFC 4180 standard

---

src/FSharp.Data.Csv.Core/CsvInference.fs
tests/FSharp.Data.Tests/CsvProvider.fs

Changed the string reader in the `parseHeaders` function to erase newline characters before it runs inferences using the input schema.
This will resolve the issue: https://github.com/fsprojects/FSharp.Data/issues/952 .
A test to check this change is added. The test passes.

Csv Column Inference ignores newline character

---

src/FSharp.Data.Csv.Core/CsvInference.fs
tests/FSharp.Data.Tests/CsvProvider.fs

This resolves the point raised at https://github.com/fsprojects/FSharp.Data/pull/1483#issuecomment-1529633129 by @nightroman
* Defined a dedicated function to read schema string to break it down into strings, separated by comma, skipping newline characters (CR/LF).
* Used `ResizeArray` to build an array of strings, so `.Length` changed to `.Count` when used.

Fix: inference on multiline csv schema

---

.github/workflows/pull-requests.yml
build.fsx
src/FSharp.Data.Http/Http.fs

Add support for plain control types

---

src/FSharp.Data.DesignTime/CommonProviderImplementation/AssemblyResolver.fs
src/FSharp.Data.DesignTime/CommonProviderImplementation/Helpers.fs
src/FSharp.Data.DesignTime/CommonProviderImplementation/QuotationBuilder.fs
src/FSharp.Data.Html.Core/HtmlOperations.fs
src/FSharp.Data.Html.Core/HtmlRuntime.fs
src/FSharp.Data.Http/Http.fs
src/FSharp.Data.Json.Core/JsonValue.fs
src/FSharp.Data.Runtime.Utilities/StructuralInference.fs
src/FSharp.Data.Runtime.Utilities/TextRuntime.fs
src/FSharp.Data.WorldBank.Core/WorldBankRuntime.fs
src/FSharp.Data.Xml.Core/XmlRuntime.fs
src/FSharp.Data.Xml.Core/XsdInference.fs

Just a minor fixes, e.g. isNull is faster than "= null".

Some code-cleanups by FSharpLint

---

src/FSharp.Data.DesignTime/CommonProviderImplementation/Helpers.fs

Trial to fix #1466: Do use separate lock-object instead of locking the array itself.
The PR uses the best practices of .NET, see:  Jeff Richter book "CLR Via C#" chapter on locks.
Or e.g. https://stackoverflow.com/questions/1873201/why-are-locks-performed-on-separate-objects

Use separate lock-object

---

paket.dependencies
paket.lock
src/FSharp.Data.Runtime.Utilities/Caching.fs
src/FSharp.Data.Runtime.Utilities/IO.fs
src/FSharp.Data.Runtime.Utilities/NameUtils.fs
src/FSharp.Data.Runtime.Utilities/StructuralInference.fs
src/FSharp.Data.Runtime.Utilities/StructuralTypes.fs
src/FSharp.Data.Runtime.Utilities/TextConversions.fs
tests/FSharp.Data.Core.Tests.CSharp/FSharp.Data.Core.Tests.CSharp.csproj
tests/FSharp.Data.Core.Tests/FSharp.Data.Core.Tests.fsproj
tests/FSharp.Data.DesignTime.Tests/FSharp.Data.DesignTime.Tests.fsproj
tests/FSharp.Data.Reference.Tests/FSharp.Data.Reference.Tests.fsproj
tests/FSharp.Data.Tests/FSharp.Data.Tests.fsproj

This is to address #1494
I'm not sure if this is enough, but at least works in my VS2022.

FSharp.Core 5.0.1 -> 6.0.1

---

.config/dotnet-tools.json
docs/library/JsonProvider.fsx

After build spending around 6h in document generation, there was an idea to update the fsdocs-tool:
https://github.com/fsprojects/FSharp.Data/pull/1496#issuecomment-1993968429

Updated fsdocs-tool to v20 stable

---

src/FSharp.Data.Csv.Core/CsvRuntime.fs
src/FSharp.Data.Html.Core/HtmlParser.fs
src/FSharp.Data.Runtime.Utilities/NameUtils.fs
src/FSharp.Data.Runtime.Utilities/TextConversions.fs

Small memory and performance optimization: 
- Less nested seq-wrapping on recursive functions
As a side note:
There are some cases where FSharp.Data does some manual recursive string-parsing-functions. More could be done on those: If we'd accept a new dependency to System.Memory on .NET Standard 2.0 version, we'd get `.AsSpan` and `ReadOnlySpan<char>` which could be used to gain speed and save memory (especially on .NET Standard 2.1 where those are available out-of-the-box and System.Memory reference is not needed).

Small memory and performance optimization: Less nested seq-wrapping on recursive functions

---

docs/library/JsonProvider.fsx
docs/library/JsonValue.fsx
src/FSharp.Data.DesignTime/WorldBank/WorldBankProvider.fs
tests/FSharp.Data.DesignTime.Tests/expected/WorldBank,World Development Indicators;Global Financial Development,True.expected

Change WorldBank url to https; fixes #1514

---

.config/dotnet-tools.json
.github/workflows/pull-requests.yml
.github/workflows/push-master.yml
.paket/Paket.Restore.targets
build.fsx
docs/data/2017_F1.htm
docs/library/HtmlProvider.fsx
docs/library/JsonProvider.fsx
docs/library/JsonValue.fsx
global.json
paket.dependencies
paket.lock
src/FSharp.Data.DesignTime/FSharp.Data.DesignTime.fsproj
src/FSharp.Data.DesignTime/WorldBank/WorldBankProvider.fs
src/FSharp.Data/FSharp.Data.fsproj
tests/FSharp.Data.Core.Tests.CSharp/FSharp.Data.Core.Tests.CSharp.csproj
tests/FSharp.Data.Core.Tests/FSharp.Data.Core.Tests.fsproj
tests/FSharp.Data.DesignTime.Tests/FSharp.Data.DesignTime.Tests.fsproj
tests/FSharp.Data.DesignTime.Tests/expected/WorldBank,World Development Indicators;Global Financial Development,True.expected
tests/FSharp.Data.Reference.Tests/FSharp.Data.Reference.Tests.fsproj
tests/FSharp.Data.Tests/FSharp.Data.Tests.fsproj

This updates:
- Fake and Paket to latest versions
- Globals.js to build on .NET 8
- Test projects from .NET 6 to .NET 8
- Also build-fixes included what are needed: 
- WorldBank to https
- Document generation fix on data source of F1 Season_Calendar
- CI-machine script updated (force-push over few trials)

Update tests to .NET 8

---

.github/workflows/push-master.yml
RELEASE_NOTES.md
docs/library/JsonProvider.fsx
docs/library/WorldBank.fsx
src/FSharp.Data.DesignTime/WorldBank/WorldBankProvider.fs

Release_notes update, 6.4.1
Also push-master.yml had .NET 6 install missing on CI machine, which I expect the build pipeline still needs.

Release_notes update, 6.4.1

---

.devcontainer/devcontainer.json
.github/dependabot.yml
Dockerfile
docker-entrypoint.sh
global.json

It should be very simple to set up a working development environment for the project. This pull request will lower the barrier to contribution from new developers as well as make it easier to replicate any errors or oddities that might occur.
VSCode's `devcontainer` feature is the closest to a turn-key solution I've found for creating portable and easy-to-setup developer environments. Github users can either choose to set up a Github codespace to work remotely in the cloud or pull down the repo and boot up the devcontainer environment in vscode.

Add vscode devcontainer config

---

src/FSharp.Data.Xml.Core/XmlRuntime.fs

Avoid ReadToEnd and use XDocument taking reader instead.
Possible fix for #1501

Avoid ReadToEnd and use XDocument taking reader instead
