fsprojects/FSharp.Data

tests/FSharp.Data.Tests/FSharp.Data.Tests.fsproj

fix malformed xml in test csproj

---

tests/FSharp.Data.DesignTime.Tests/SignatureTestCases.config
tests/FSharp.Data.DesignTime.Tests/expected/Csv,DnbHistoriskeKurser.csv,,,True,False,False,,pt-PT,.expected
tests/FSharp.Data.Tests/CsvProvider.fs

Was getting tired of this test failing to compile on my machine

Workaround for #767

---

src/AssemblyInfo.DesignTime.fs
src/AssemblyInfo.Portable47.fs
src/AssemblyInfo.Portable7.fs
src/AssemblyInfo.fs
src/Csv/CsvGenerator.fs
src/FSharp.Data.DesignTime.fsproj
src/FSharp.Data.Portable47.fsproj
src/FSharp.Data.Portable7.fsproj
src/FSharp.Data.fsproj
src/Html/HtmlGenerator.fs
src/Json/JsonProvider.fs
src/WorldBank/WorldBankProvider.fs
src/Xml/XmlProvider.fs
tests/FSharp.Data.DesignTime.Tests/FSharp.Data.DesignTime.Tests.fsproj
tests/FSharp.Data.Tests/FSharp.Data.Tests.fsproj
tests/FSharp.Data.Tests/XmlProvider.fs
tests/TestApps/ConsoleApp_4300_Library_4300/ConsoleApp_4300_Library_4300.fsproj
tests/TestApps/ConsoleApp_4300_PCL47_2350/ConsoleApp_4300_PCL47_2350.fsproj
tests/TestApps/ConsoleApp_4310_Library_4300/ConsoleApp_4310_Library_4300.fsproj
tests/TestApps/ConsoleApp_4310_Library_4310/ConsoleApp_4310_Library_4310.fsproj
tests/TestApps/ConsoleApp_4310_PCL47_2350/ConsoleApp_4310_PCL47_2350.fsproj
tests/TestApps/ConsoleApp_4310_PCL7_3310/ConsoleApp_4310_PCL7_3310.fsproj
tests/TestApps/Library_4300/Library_4300.fsproj
tests/TestApps/Library_4310/Library_4310.fsproj
tests/TestApps/PCL47_2350/PCL47_2350.fsproj
tests/TestApps/PCL47_2351/PCL47_2351.fsproj
tests/TestApps/PCL7_3310/PCL7_3310.fsproj

* Fix fsproj files
* Fix new warnings
* Make all provided types non nullable

Support for F# 4.0

---

src/CommonRuntime/TextConversions.fs

See #786 Performance of Csv Type Provider and CsvFile

Cache DefaultRemovableAdornerCharacters for performance

---

src/Net/Http.fs
tests/FSharp.Data.Tests/HttpIntegrationTests.fs

Use content type encoding

---

src/CommonProviderImplementation/AssemblyResolver.fs

A better fix for the #821 issue, as suggested by @veikkoeeva. I tested this on my Azure VM and it worked fine.

Use ApplyPolicy with ReflectionOnlyLoad based on name (improve #821)

---

src/CommonRuntime/Caching.fs

cacheFolder on Unix is ~/.cache/fsharp-data

---

src/Json/JsonValue.fs

...by pre-allocating StringBuilder, and ResizeArray for records and arrays. Also, reduce allocations and ops during numeric parsing by avoiding use of Option and active patterns.
This resulted in about a 20% parsing performance improvement in terms of time, as well as reduced gen 0 and gen 1 collections:
> Real: 00:00:25.131, CPU: 00:00:25.109, GC gen0: 3445, gen1: 4, gen2: 1
vs 
> Real: 00:00:19.631, CPU: 00:00:19.640, GC gen0: 1689, gen1: 3, gen2: 1
The test parsed a 4KB JSON string 500k times.
For comparison, parsing using `Newtonsoft.Json.Linq.JToken.Parse` recorded:
> Real: 00:00:38.252, CPU: 00:00:38.234, GC gen0: 3363, gen1: 305, gen2: 1

Improve parsing performance

---

src/Net/Http.fs
tests/FSharp.Data.Tests/HttpIntegrationTests.fs
tests/FSharp.Data.Tests/MockServer.fs

Handle cookies with "http://"-prefixed domain value.

---

src/Net/Http.fs

Whoops, this should resolve #910.

Fix cookie domain parsing blooper

---

src/Csv/CsvRuntime.fs
tests/FSharp.Data.Tests/CsvProvider.fs
tests/FSharp.Data.Tests/Http.fs

fix for issue #978: replacing null with empty string when writing

---

.travis.yml

Travis seems toast, this tries to resurrect

Try to resurrect Travis CI

---

src/Html/HtmlParser.fs
tests/FSharp.Data.Tests/HtmlParser.fs

Fix for issue #1014

---

tests/FSharp.Data.Tests/JsonParserProperties.fs

Fixed failing unit test when running under console test runner

---

build.fsx
paket.lock

see https://github.com/fsharp/FAKE/issues/1515

Update FAKE version

---

tests/FSharp.Data.DesignTime.Tests/expected/WorldBank,World Development Indicators;Global Financial Development,True.expected

The Wold Bank data was updated, so expected file should be updated as well.

The expected file for World Bank was updated

---

src/CommonRuntime/StructuralInference.fs
tests/FSharp.Data.Tests/CsvProvider.fs

Create a failing test for #1083

---

docs/content/library/HtmlCssSelectors.fsx

Tried using `https://www.packtpub.com/all?search=f%23` but have rather inconvenient DOM structure in my opinion.

Updated HttpCssSelector documentation

---

docs/content/library/CsvFile.fsx

Hi! First pull request on a F# Open Source project.
I have used mono's fsharpi (on Mac OS X) to run the CsvFile.fsx to verify things work after the changes.
Please, let me know your comments, in case I should do things differently.

Fixes #1086 https://github.com/fsharp/FSharp.Data/issues/1086

---

docs/content/library/JsonProvider.fsx

JSONProvider SampleIsList parameter documentation

---

tests/FSharp.Data.Tests/Http.fs

fix form data test intermittent failure

---

docs/content/ja/contributing.md
docs/content/ja/library/CsvProvider.fsx
docs/content/library/CsvProvider.fsx
src/CommonProviderImplementation/AssemblyResolver.fs
src/CommonProviderImplementation/ConversionsGenerator.fs
src/CommonProviderImplementation/Helpers.fs
src/CommonProviderImplementation/QuotationBuilder.fs
src/Csv/CsvGenerator.fs
src/Csv/CsvProvider.fs
src/Html/HtmlGenerator.fs
src/Html/HtmlProvider.fs
src/Json/JsonConversionsGenerator.fs
src/Json/JsonExtensions.fs
src/Json/JsonGenerator.fs
src/Json/JsonProvider.fs
src/Runtime.fs
src/WorldBank/WorldBankProvider.fs
src/Xml/XmlGenerator.fs
src/Xml/XmlProvider.fs
tests/FSharp.Data.Tests/CsvProvider.fs
tests/FSharp.Data.Tests/HtmlProvider.fs

To make the .Net Standard PR smaller

Replace Microsoft.FSharp with FSharp

---

src/Net/Http.fs

Fix for function getAllCookiesFromHeader where cookie string is empty no cookie needs to be created.

Fix for Issue #982: "part of the cookie is invalid"

---

RELEASE_NOTES.md
src/Xml/XmlRuntime.fs
tests/FSharp.Data.Tests/XmlProvider.fs

https://github.com/fsharp/FSharp.Data/issues/1017#issuecomment-380422441

#1017 Preserve whitespace in between tags

---

RELEASE_NOTES.md
src/Xml/XmlRuntime.fs
src/Xml/XsdInference.fs
tests/FSharp.Data.DesignTime.Tests/expected/Xml,,False,False,,False,po.xsd.expected
tests/FSharp.Data.Tests/Data/po.xsd
tests/FSharp.Data.Tests/XmlProvider.fs

distinguish date and dateTime according to #1181

Improve XSD date handling (#1181)

---

docs/content/ja/library/CsvProvider.fsx
docs/content/ja/library/WorldBank.fsx
docs/content/library/CsvProvider.fsx
docs/content/library/HtmlProvider.fsx
docs/content/library/WorldBank.fsx
performanceAnalysis.fsx

Fix path for fsharp.charting.fsx. Travis shall be green now.

Update path for fsharp.charting.fsx

---

tests/FSharp.Data.Tests/HtmlParser.fs

Test html parsing of script with '/' embedded in bracketed character class

---

src/CommonProviderImplementation/Helpers.fs
src/Csv/CsvProvider.fs
src/Html/HtmlProvider.fs
src/Json/JsonProvider.fs
src/Xml/XmlProvider.fs
tests/FSharp.Data.DesignTime.Tests/expected/Json,Dates.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,DoubleNested.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,Empty.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,GitHub.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,Nested.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,OptionValues.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,Simple.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,SimpleArray.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,TimeSpans.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,TwitterSample.json,True,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,TwitterStream.json,True,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,TypeInference.json,False,,,False.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,TypeInference.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,Vindinium.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,WikiData.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,WorldBank.json,False,WorldBank,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,contacts.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,optionals.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,projects.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,reddit.json,False,,,True.expected
tests/FSharp.Data.DesignTime.Tests/expected/Json,topics.json,True,Topic,,True.expected
tests/FSharp.Data.Tests/JsonProvider.fs

Add ParseList on JsonProvider

---

.paket/Paket.Restore.targets
RELEASE_NOTES.md
paket.lock
tests/FSharp.Data.DesignTime.Tests/InferenceTests.fs

Fixes a problem with using FSHarp.Data on .NET Core F# Interactive

Update to latest TPSDK

---

FSharp.Data.Tests.sln
build.fsx
tests/FSharp.Data.Reference.Tests/FSharp.Data.Reference.Tests.fsproj
tests/FSharp.Data.Reference.Tests/JsonProvider.fs
tests/FSharp.Data.Reference.Tests/Program.fs
tests/FSharp.Data.Reference.Tests/app.config
tests/FSharp.Data.Tests/FSharp.Data.Tests.fsproj
tests/FSharp.Data.Tests/JsonProvider.fs

I take old version of FSharp.TypeProviders.SDK
Fix issue #1255

Fix issue #1255 : EmbeddedResource not working

---

CODE_OF_CONDUCT.MD
README.md

Also some small cleanup in the readme

Add code of conduct

---

FSharp.Data.sln
docs/ja/contributing.md
docs/ja/library/JsonValue.fsx
docs/library/CsvFile.fsx
docs/library/CsvProvider.fsx
docs/library/HtmlCssSelectors.fsx
docs/library/HtmlParser.fsx
docs/library/Http.fsx
docs/library/JsonProvider.fsx
docs/library/JsonValue.fsx
docs/library/WorldBank.fsx
docs/library/XmlProvider.fsx
docs/tutorials/JsonAnonymizer.fsx
docs/tutorials/JsonToXml.fsx

Using the new API reference doc links

Use api doc links

---

.config/dotnet-tools.json
docs/library/CsvFile.fsx
docs/library/CsvProvider.fsx
docs/library/HtmlCssSelectors.fsx
docs/library/HtmlParser.fsx
docs/library/HtmlProvider.fsx
docs/library/Http.fsx
docs/library/JsonProvider.fsx
docs/library/JsonValue.fsx
docs/library/XmlProvider.fsx
docs/tutorials/JsonAnonymizer.fsx
docs/tutorials/JsonToXml.fsx

Use the new doc categorization metadata feature of fsdocs
https://fsprojects.github.io/FSharp.Formatting/content.html#Front-matter

doc categories

---

src/CommonRuntime/Pluralizer.fs

Add plural for "source"

---

paket.lock

Updated ProvidedTypes.fs

---

paket.lock
src/FSharp.Data.Runtime.Utilities/StructuralTypes.fs

TypeProvider SDK update.
Also compiler warning fix.

TypeProvider SDK update.

---

src/FSharp.Data.Csv.Core/CsvRuntime.fs

fix missing space

---

paket.lock

Latest ProvidedTypes update from FSharp.TypeProvider.SDK

Latest ProvidedTypes update from FSharp.TypeProvider.SDK
